[package]
authors = ["Rowan Herbert <rlherbert.dev@gmail.com>"]
edition = "2018"
name = "generic_sort"
version = "1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
